# Generated by Django 2.1.5 on 2019-01-24 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 1, 24, 19, 26, 21, 349642), verbose_name='Created at')),
                ('modified_at', models.DateTimeField(default=datetime.datetime(2019, 1, 24, 19, 26, 21, 349642), verbose_name='Modified at')),
                ('title', models.CharField(default='<title>', max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='products')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
