# Generated by Django 2.1.5 on 2019-01-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190124_1948'),
    ]

    operations = [
    ]
