# Generated by Django 2.1.5 on 2019-01-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190124_1953'),
    ]

    operations = [
    ]
